version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    command: [start-kafka.sh]
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CREATE_TOPICS: "bonus-transaction:1:1, bonus-notbank:1:1"
    depends_on:
      - "zookeeper"

  postgres:
    image: postgres:11
    container_name: roshack-db
    environment:
      POSTGRES_USER: roshack
      POSTGRES_PASSWORD: roshack
      POSTGRES_DB: roshack
    ports:
      - 5432:5432

  redis:
    image: redis
    container_name: redis-cache-container